language: python
python:
  - "3.6"
env:
  global:
    - PYPI_USERNAME=autopub
    - secure: "h5V/+YL+CrqvfAesNkSb824Ngk5x+f0eFzj/LBbmnzjvArKAmc6R6WGyx8SDD7WF/PlaTf0M1fH3a7pjIS8Ee+TS1Rb0Lt1HPqUs1yntg1+Js2ZQp3p20wfsDc+bZ4/2g8xLsSMv1EJ4np7/GJ5fXqpSxjr/Xs5LYA7ZLwNNwDw="
    - secure: "GiDFfmjH7uzYNnkjQMV/mIkbRdmgkGmtbFPeaj9taBNA5tPp3IBt3GOOS6UL/zm9xiwu9Xo6sxZWkGzY19Hsdv28YPH34N3abo0QSnz4IGiHs152Hi7Qi6Tb0QkT5D3OxuSIm8LmFL7+su89Q7vBFowrT6HL1Mn8CDDWSj3eqbo="
    - TWINE_USERNAME=$PYPI_USERNAME
    - TWINE_PASSWORD=$PYPI_PASSWORD
  matrix:
    - TOX_ENV=docs
    - TOX_ENV=flake8
    - TOX_ENV=py27
    - TOX_ENV=py35
    - TOX_ENV=py36
matrix:
  include:
    - python: 3.7
      sudo: true
      dist: xenial
      env:
      - TOX_ENV=py37
addons:
  apt_packages:
    - pandoc
before_install:
  - sudo apt-get update -qq
  - sudo locale-gen fr_FR.UTF-8 tr_TR.UTF-8
install:
  - pip install tox==2.5.0
script: tox -e $TOX_ENV
before_deploy:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then travis_terminate 0; fi'
  - pip install githubrelease
  - pip install --pre autopub
  - autopub check || travis_terminate 0
  - pip install poetry
  - pip install twine
  - git checkout ${TRAVIS_BRANCH}
  - git remote set-url origin https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG
deploy:
  provider: script
  script: autopub deploy
  skip_cleanup: true
  on:
    branch: master
    python: "3.7"
# The channel name "irc.freenode.org#pelican" is encrypted against getpelican/pelican to prevent IRC spam of forks
notifications:
  irc:
    channels:
      - secure: "JP57f61QovrhmLoAF6oPOzIK2aXGfSO06FHg7yiuKBOWMiaxQejZUGJX919muCLhWJXDugsviIqCMoAWwNV3o1WQbqIr+G5TR+N9MrtCs4Zi6vpGj09bR8giKUKx+PPKEoe1Ew56E4y2LxzGO4Lj9hZx8M2YVdwPNWrWZgp6WXE="
    on_success: change
